version: '2'
services:
    # This will create a MySQL server
    # and store data in "./mysql" (in project directory)
    #
    # You can connect to it using:
    # mysql -u root -proot -h 127.0.0.1
    db:
        image: mysql/mysql-server
        ports:
            - "3306:3306"
        expose:
            - "3306"
        volumes:
            - ../../.data/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root

    #
    # Apache with PHP 7.0 will be on http://localhost:8005
    #
    #application:
    #    build: ../../containers/apache-php70
    #    ports:
    #        - "8005:80"
    #    expose:
    #        - "80"
    #    volumes:
    #        - ../../../:/var/www/html
    #    links:
    #        - db

    #
    # Apache with PHP 5.6
    #
    application_56:
        build: ../../containers/apache-php56
        ports:
            - "8002:80"
        expose:
            - "80"
        volumes:
            - ../../../:/var/www/html
        links:
            - db

    # Alternative to phpMyAdmin
    # will be available on http://localhost:8003
    mysql_admin:
        build: ../../containers/chive
        ports:
            - "8003:8003"

    # Database administration web gui
    # accessible via http://localhost:8003
    #db_admin:
    #    image: phpmyadmin/phpmyadmin
    #    ports:
    #        - "80:8003"
    #    expose:
    #        - "80"
    #    links:
    #        - db